Update tsconfig.json
fix ﻿2026-06-07T00:18:00.2892753Z ##[group]Run npm run build
npm run build
shell: /usr/bin/bash -e {0}

> biblical-views@0.0.1 build
> tsc && vite build

src/biblical-views.tsx(41,26): error TS2339: Property 'env' does not exist on type 'ImportMeta'.
Process completed with exit code 2.